name: Build Utility Images

on:
  # Uncomment below for testing purposes
  # pull_request:
  push:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    strategy:
      matrix:
        include:
          - image: lando-util
            tag: 4
            context: plugins/lando-core/types/utility

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set tag suffix
        id: pr
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "::set-output name=TAG_SUFFIX::-edge"
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: https://ghcr.io
      - name: Build and push ghcr.io/automattic/vip-container-images/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/automattic/vip-container-images/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
